### ISSUE TITLE
[Other]: "Faggot" word in your code

### ISSUE THREAD

**Issue by badger-codes** [misspent/Darkened-Stylus-Themes#3]
### 🔍 Did you check former issues/requests?

- [X] I have checked other issues

### 📝 Describe what you want

you probably want to take the word "faggot" out of your code, professionally, ethically, and reputationally speaking. this is coming from a homosexual, so don't even start with me.

**Comment by misspent** [comment]
It wasn't in it for any reason other than me calling myself a faggot or some other slur because of how many facepalm moments I have; honestly, I didn't even know I had that in the code, so it must've been a while ago.

Rather shocked you noticed that in the code.





**Edit**: I assume you're on about the DuckDuckGo theme?
